source 'https://rubygems.org'

gem 'rails', '4.0.2'

gem 'pg'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

gem 'devise'
gem 'rails_admin'
gem 'cancan'
gem 'paper_trail'

gem 'pry-nav'