source 'https://rubygems.org'

gem 'rails', '4.0.2'

gem 'pg'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

gem 'auth_lib', path: '../auth_lib'
gem 'rails_admin'
gem 'rails_admin_state'
gem 'rails_admin_process', path: '../rails_admin_process'
gem 'paper_trail'

gem 'state_machine'
gem 'enumerize'
gem 'date_validator'
gem 'countries'

gem 'thin'

gem 'mq_connector', path: '../mq_connector'

gem 'pry-nav'